# Generated by Django 3.2 on 2021-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0005_mascota_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='usuario',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
