# Generated by Django 3.2 on 2021-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0008_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cate'),
        ),
    ]
