# Generated by Django 3.2 on 2021-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0009_tipomascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='mascotas/sin_foto.jpg', upload_to='mascotas'),
        ),
    ]
